In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, roc_curve, auc,ConfusionMatrixDisplay

In [4]:
df=pd.read_csv('..\Capstone-2-Data-wranglling\preprocessed.csv',index_col='id')

In [5]:
df

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
id,,,,,,,,,,,
9046,Male,1.051242,0,1,Yes,Private,Urban,2.706450,1.004893,formerly smoked,1
51676,Female,0.785889,0,0,Yes,Self-employed,Rural,2.121652,-0.099142,never smoked,1
31112,Male,1.626174,0,1,Yes,Private,Rural,-0.004867,0.472358,never smoked,1
60182,Female,0.255182,0,0,Yes,Private,Urban,1.437473,0.719142,smokes,1
1665,Female,1.581949,1,0,Yes,Self-employed,Rural,1.501297,-0.631677,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
18234,Female,1.626174,1,0,Yes,Private,Urban,-0.494481,-0.099142,never smoked,0
44873,Female,1.670400,0,0,Yes,Self-employed,Urban,0.420922,1.446507,never smoked,0
19723,Female,-0.363976,0,0,Yes,Self-employed,Rural,-0.511266,0.225574,never smoked,0
37544,Male,0.343633,0,0,Yes,Private,Rural,1.328375,-0.423859,formerly smoked,0
44679,Female,0.034054,0,0,Yes,Govt_job,Urban,-0.460692,-0.345927,Unknown,0

In [15]:
X_train=pd.read_csv('..\Capstone-2-Data-wranglling\X_train.csv',index_col='id')

In [16]:
X_train

,age,hypertension,heart_disease,avg_glucose_level,bmi,gender_Female,gender_Male,ever_married_No,ever_married_Yes,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes
id,,,,,,,,,,,,,,,,,,,,
45163,0.166731,0,0,-0.149742,-0.657654,1,0,0,1,0,0,1,0,0,0,1,0,0,0,1
22330,0.078280,0,0,-0.512370,0.056721,1,0,0,1,0,0,0,1,0,0,1,1,0,0,0
43016,-1.469615,0,0,-0.782684,-0.449836,0,1,1,0,0,0,0,0,1,0,1,1,0,0,0
40980,1.581949,1,0,-0.753091,-0.683631,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0
1183,-0.187073,0,0,-0.484985,-0.099142,0,1,0,1,0,0,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67217,0.078280,0,0,-0.293291,0.810063,1,0,0,1,0,0,1,0,0,0,1,0,1,0,0
34376,-1.204261,0,0,0.161871,-1.216166,1,0,1,0,0,0,0,0,1,1,0,1,0,0,0
10752,0.785889,0,0,-0.607112,0.952938,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0
56939,0.520535,0,0,-0.290641,-0.423859,1,0,0,1,0,0,0,1,0,1,0,0,0,1,0
43496,0.122505,0,0,-1.110861,-0.138108,1,0,0,1,1,0,0,0,0,0,1,0,0,1,0